\documentclass[10pt]{article}

\usepackage{amsmath,amssymb,amsthm}
\usepackage{fancyhdr,url,hyperref}
\usepackage{enumerate,multirow}

\oddsidemargin 0in  %0.5in
\topmargin     0in
\leftmargin    0in
\rightmargin   0in
\textheight    9in
\textwidth     6in %6in

\pagestyle{fancy}

\lhead{\textsc{MATH 141}}
\chead{\textsc{Problem Set 3}}
\lfoot{}
\cfoot{}
%\cfoot{\thepage}
\rfoot{}
\renewcommand{\headrulewidth}{0.2pt}
\renewcommand{\footrulewidth}{0.0pt}

\newcommand{\ans}{\vspace{0.25in}}
\newcommand{\R}{{\sf R}\xspace}
\newcommand{\cmd}[1]{\texttt{#1}}

\title{MATH 141:\\Intro to Probability and Statistics}
\author{Prof. Bray}
\date{Spring 2016}

\rhead{\textsc{Spring 2016}}

\begin{document}
%\SweaveOpts{concordance=TRUE}

\begin{enumerate}
\item The American Community 
Survey is an ongoing survey that provides data every year to give communities the 
current information they need to plan investments and services. The 2010 American 
Community Survey estimates that 14.6\% of Americans live below the poverty line, 
20.7\% speak a language other than English (foreign language) at home, and 4.2\% 
fall into both categories.
\begin{enumerate}[(a)]
\item Are living below the poverty line and speaking a foreign language at home 
disjoint?
\item Draw a Venn diagram summarizing the variables and their associated 
probabilities.
\item What percent of Americans live below the poverty line and only speak 
English at home?
\item What percent of Americans live below the poverty line or speak a foreign 
language at home?
\item What percent of Americans live above the poverty line and only speak 
English at home? 
\item Is the event that someone lives below the poverty line independent of the 
event that the person speaks a foreign language at home?
\end{enumerate}


\item In parts~(a) and~(b), 
identify whether the events are disjoint, independent, or neither (events cannot 
be both disjoint and independent).
\begin{enumerate}[(a)]
\item You and a randomly selected student from your class both earn A's in this 
course. 
\item You and your class study partner both earn A's in this course.
\item If two events can occur at the same time, must they be dependent?
\end{enumerate}


\item Data collected at elementary 
schools in DeKalb County, GA suggest that each year roughly 25\% of students miss 
exactly one day of school, 15\% miss 2 days, and 28\% miss 3 or more days due to 
sickness.
\begin{enumerate}[(a)]
\item What is the probability that a student chosen at random doesn't miss any 
days of school due to sickness this year?
\item What is the probability that a student chosen at random misses no more than 
one day?
\item What is the probability that a student chosen at random misses at least one 
day?
\item If a parent has two kids at a DeKalb County elementary school, what is the 
probability that neither kid will miss any school? Note any assumption you must 
make to answer this question.
\item If a parent has two kids at a DeKalb County elementary school, what is the 
probability that both kids will miss some school, i.e. at least one day? Note any 
assumption you make.
\item If you made an assumption in part~(d) or~(e), do you think it was 
reasonable? If you didn't make any assumptions, double check your earlier answers.
\end{enumerate}

\item $\mathbb{P}(A) = 0.3$, 
$\mathbb{P}(B) = 0.7$
\begin{enumerate}[(a)]
\item Can you compute $\mathbb{P}(A \text{ and } B)$ if you only know $\mathbb{P}(A)$ and $\mathbb{P}(B)$?
\item Assuming that events $A$ and $B$ arise from independent random processes,
\begin{enumerate}[(i)]
\item what is $\mathbb{P}(A \text{ and } B)$?
\item what is $\mathbb{P}(A \text{ or } B)$?
\item what is $\mathbb{P}(A \,|\, B)$?
\end{enumerate}
\item If we are given that $\mathbb{P}(A \text{ and } B) = 0.1$, are the random variables giving rise 
to events $A$ and $B$ independent?
\item If we are given that $\mathbb{P}(A \text{ and } B) = 0.1$, what is $\mathbb{P}(A \,|\, B)$?
\end{enumerate}

\item A 2010 Pew Research poll asked 
1,306 Americans ``From what you've read and heard, is there solid evidence that 
the average temperature on earth has been getting warmer over the past few 
decades, or not?". The table below shows the distribution of responses by party 
and ideology, where the counts have been replaced with relative frequencies.
\begin{center}
\begin{tabular}{ll  ccc c} 
                    &                           & \multicolumn{3}{c}{\textit{Response}} \\
\cline{3-5}
                    &                           & Earth is  & Not       & Don't Know    &   \\
                    &                           & warming   & warming   & Refuse        & Total\\
\cline{2-6}
                    & Conservative Republican   & 0.11      & 0.20      & 0.02      & 0.33  \\
\textit{Party and}  & Mod/Lib Republican        & 0.06      & 0.06      & 0.01      & 0.13 \\
\textit{Ideology}   & Mod/Cons Democrat         & 0.25      & 0.07      & 0.02      & 0.34 \\
                    & Liberal Democrat          & 0.18      & 0.01      & 0.01      & 0.20\\
\cline{2-6}
                    &Total                      & 0.60      & 0.34      & 0.06      & 1.00
\end{tabular}
\end{center}
\begin{enumerate}[(a)]
\item Are believing that the earth is warming and being a liberal Democrat mutually 
exclusive?
\item What is the probability that a randomly chosen respondent believes the 
earth is warming or is a liberal Democrat?
\item What is the probability that a randomly chosen respondent believes the 
earth is warming given that he is a liberal Democrat?
\item What is the probability that a randomly chosen respondent believes the 
earth is warming given that he is a conservative Republican?
\item Does it appear that whether or not a respondent believes the earth is 
warming is independent of their party and ideology? Explain your reasoning.
\item What is the probability that a randomly chosen respondent is a 
moderate/liberal Republican given that he does not believe that the earth is 
warming? 
\end{enumerate}

\item After an introductory 
statistics course, 80\% of students can successfully construct box plots. Of 
those who can construct box plots, 86\% passed, while only 65\% of those students 
who could not construct box plots passed.
\begin{enumerate}[(a)]
\item Construct a tree diagram of this scenario.
\item Calculate the probability that a student is able to construct a box plot 
if it is known that he passed.
\end{enumerate}


\item Lupus is a medical phenomenon where 
antibodies that are supposed to attack foreign cells to prevent infections 
instead see plasma proteins as foreign bodies, leading to a high risk of blood 
clotting. It is believed that 2\% of the population suffer from this disease. The 
test is 98\% accurate if a person actually has the disease. The test is 74\% 
accurate if a person does not have the disease. There is a line from the Fox 
television show \emph{House} that is often used after a patient tests positive 
for lupus: ``It's never lupus." Do you think there is truth to this statement? 
Use appropriate probabilities to support your answer.


\item At a university, 13\% of 
students smoke.
\begin{enumerate}[(a)]
\item Calculate the expected number of smokers in a random sample of 100 students 
from this university.
\item The university gym opens at 9 am on Saturday mornings. One Saturday morning 
at 8:55 am there are 27 students outside the gym waiting for it to open. Should 
you use the same approach from part (a) to calculate the expected number of 
smokers among these 27 students?
\end{enumerate}


\item Consider the following card game 
with a well-shuffled deck of cards. If you draw a red card, you win nothing. If 
you get a spade, you win \$5. For any club, you win \$10 plus an extra \$20 for 
the ace of clubs.
\begin{enumerate}[(a)]
\item Create a probability model for the amount you win at this game. Also, find 
the expected winnings for a single game and the standard deviation of the 
winnings.
\item What is the maximum amount you would be willing to pay to play this game? 
Explain your reasoning.
\end{enumerate}


\item An airline charges the following 
baggage fees: \$25 for the first bag and \$35 for the second. Suppose 54\% of 
passengers have no checked luggage, 34\% have one piece of checked luggage and 
12\% have two pieces. We suppose a negligible portion of people check more than 
two bags.
\begin{enumerate}[(a)]
\item Build a probability model, compute the average revenue per passenger, and 
compute the corresponding standard deviation.
\item About how much revenue should the airline expect for a flight of 120 
passengers? With what standard deviation? Note any assumptions you make and if 
you think they are justified.
\end{enumerate}


\item The relative frequency table 
below displays the distribution of annual total personal income (in 2009 
inflation-adjusted dollars) for a representative sample of 96,420,486 Americans. 
These data come from the American Community Survey for 2005-2009. This sample is 
comprised of 59\% males and 41\% females. \\

\noindent\begin{minipage}[c]{0.60\textwidth}
\begin{enumerate}[(a)]
\item Describe the distribution of total personal income.
\item What is the probability that a randomly chosen US resident makes less than 
\$50,000 per year?
\item What is the probability that a randomly chosen US resident makes less than 
\$50,000 per year and is female? Note any assumptions you make.
\item The same data source indicates that 71.8\% of females make less than 
\$50,000 per year. Use this value to determine whether or not the assumption you 
made in part (c) is valid.
\end{enumerate}
\end{minipage}
\begin{minipage}[c]{0.4\textwidth}
{\small
\begin{center}
\begin{tabular}{lr}
  \hline
\textit{Income}         & \textit{Total} \\
  \hline
\$1 to \$9,999 or loss  & 2.2\% \\
\$10,000 to \$14,999    & 4.7\% \\
\$15,000 to \$24,999    & 15.8\% \\
\$25,000 to \$34,999    & 18.3\% \\
\$35,000 to \$49,999    & 21.2\% \\
\$50,000 to \$64,999    & 13.9\% \\
\$65,000 to \$74,999    & 5.8\% \\
\$75,000 to \$99,999    & 8.4\% \\
\$100,000 or more       & 9.7\% \\
   \hline
\end{tabular}
\end{center}
}
\end{minipage}

\end{enumerate}

\textbf{Extra Challenge Problem:} A \emph{chord} of a circle is a straight line 
segment whose endpoints both lie on the circle. For a fixed circle, what is
the probability that the length of a randomly drawn chord will exceed that
circle's radius?

\end{document}